/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loimgui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.Set;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import model.DBModel;
import model.IModel;
import model.Kerdesek;
import loimgui.Kerdezo;

/**
 *
 * @author Bodnár Tamás <tms.bodnar@gmail.com> | www.kalandlabor.hu
 */
public class Foablak extends javax.swing.JFrame {

    private IModel model;
    private Vector<Kerdesek> kerdesek;
    private Kerdesek kerdes;
    private Kerdezo kerdezo;
    int nyeremeny;
    int kerdesSzam;
    Set<Integer> sorszam;
    Iterator<Integer> it;
    private boolean helyes;
    boolean telo = true;
    boolean kozonseg = true;
    boolean felezo = true;
    private String[] nyeremenyek = {"40.000.000 Ft", "20.000.000 Ft", "10.000.000 Ft", "5.000.000 Ft",
        "2.000.000Ft", "1.000.000 Ft", "800.000 Ft", "500.000 Ft", "300.000 Ft", "200.000 Ft",
        "100.000 Ft", "50.000 Ft", "20.000 Ft", "10.000 Ft", "5.000 Ft"};

    /**
     * Creates new form Foablak
     */
    public Foablak() {
        initComponents();
        setTitle("Legyen Ön is milliomos!");
        setLocationRelativeTo(null);
        String connUrl = "jdbc:mysql://localhost:3306/java_vizsga";
        String user = "root";
        String pass = "1234";
        lstNyeremeny.setListData(nyeremenyek);
        this.kerdezo = kerdezo;
        JProgressBar JProgressBar2 = new JProgressBar();
        jProgressBar2.setValue(kerdesSzam);

        try {
            Connection conn = DriverManager.getConnection(connUrl, user, pass);
            model = new DBModel(conn);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKozonseg = new javax.swing.JToggleButton();
        btnFelezo = new javax.swing.JToggleButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNyeremeny = new javax.swing.JList<>();
        tfKerdes = new javax.swing.JTextField();
        tfKerdezo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnValasz1 = new javax.swing.JButton();
        btnValasz0 = new javax.swing.JButton();
        btnValasz2 = new javax.swing.JButton();
        btnValasz3 = new javax.swing.JButton();
        btnIgen = new javax.swing.JButton();
        btnNem = new javax.swing.JButton();
        btnTelefon = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmJatek = new javax.swing.JMenu();
        jmUjJatek = new javax.swing.JMenuItem();
        jmKilepes = new javax.swing.JMenuItem();
        jmKerdesek = new javax.swing.JMenu();
        jmKerdesSzerkeszto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKozonseg.setText("Közönség véleménye");
        btnKozonseg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKozonsegActionPerformed(evt);
            }
        });

        btnFelezo.setText("Válasz felező");
        btnFelezo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFelezoActionPerformed(evt);
            }
        });

        jProgressBar2.setMaximum(15);
        jProgressBar2.setOrientation(1);
        jProgressBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 153), new java.awt.Color(0, 102, 204)));
        jProgressBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBar2.setString("Ft");

        lstNyeremeny.setBackground(java.awt.SystemColor.control);
        lstNyeremeny.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10", "Item 11", "Item 12", "Item 13", "Item 14", "Item 15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstNyeremeny.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNyeremeny.setToolTipText("");
        jScrollPane1.setViewportView(lstNyeremeny);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnValasz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz1ActionPerformed(evt);
            }
        });

        btnValasz0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz0ActionPerformed(evt);
            }
        });

        btnValasz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz2ActionPerformed(evt);
            }
        });

        btnValasz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz3ActionPerformed(evt);
            }
        });

        btnIgen.setText("Igen");
        btnIgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgenActionPerformed(evt);
            }
        });

        btnNem.setText("Nem");
        btnNem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNemActionPerformed(evt);
            }
        });

        btnTelefon.setText("Telefonos segítség");
        btnTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonActionPerformed(evt);
            }
        });

        jmJatek.setText("Játék");

        jmUjJatek.setText("Új játék");
        jmUjJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUjJatekActionPerformed(evt);
            }
        });
        jmJatek.add(jmUjJatek);

        jmKilepes.setText("Kilépés");
        jmKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmKilepesActionPerformed(evt);
            }
        });
        jmJatek.add(jmKilepes);

        jMenuBar1.add(jmJatek);

        jmKerdesek.setText("Kérdések");

        jmKerdesSzerkeszto.setText("Kérdések szerkesztése");
        jmKerdesSzerkeszto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmKerdesSzerkesztoActionPerformed(evt);
            }
        });
        jmKerdesek.add(jmKerdesSzerkeszto);

        jMenuBar1.add(jmKerdesek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfKerdes)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfKerdezo, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIgen)
                        .addGap(18, 18, 18)
                        .addComponent(btnNem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnValasz0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnValasz2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnValasz3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(btnValasz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnKozonseg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFelezo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addComponent(btnTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFelezo, btnKozonseg});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTelefon)
                        .addGap(11, 11, 11)
                        .addComponent(btnKozonseg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFelezo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfKerdezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnIgen)
                                .addComponent(btnNem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnValasz1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnValasz0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnValasz3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnValasz2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmKilepesActionPerformed
        if (model != null) {
            try {
                model.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
            }
            System.exit(0);
        }
    }//GEN-LAST:event_jmKilepesActionPerformed

    private void jmUjJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUjJatekActionPerformed
        kerdezo = new Kerdezo();
        kerdezo.setHelyes(true);
        kerdesSzam = 1;
        nyeremeny = 15;
        helyes = true;

        try {
            kerdesek = model.getAllKerdes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
        }
        kerdezo.setKerdesek(kerdesek);
        btnTelefon.setSelected(false);
        btnKozonseg.setSelected(false);
        btnFelezo.setSelected(false);
                
        jatek();
    }

    public void jatek() {
        if (helyes) {
            kerdes = kerdezo.getKerdezo(kerdesSzam - 1);
            jProgressBar2.setValue(kerdesSzam);
            lstNyeremeny.setSelectedIndex(15 - kerdesSzam);

            if (kerdesSzam == 1) {
                tfKerdezo.setText("Az első kérdés:");
            } else {
                tfKerdezo.setText(" A " + (kerdesSzam) + ". kérdés a következő:");
            }

            tfKerdes.setText(kerdes.getKerdes());
            btnValasz0.setText("<html>"+kerdes.getValasz0()+"</html>");
            btnValasz1.setText("<html>"+kerdes.getValasz1()+"</html>");
            btnValasz2.setText("<html>"+kerdes.getValasz2()+"</html>");
            btnValasz3.setText("<html>"+kerdes.getValasz3()+"</html>");
        }
    }//GEN-LAST:event_jmUjJatekActionPerformed

    private void jmKerdesSzerkesztoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmKerdesSzerkesztoActionPerformed
        JelszoKero jk = new JelszoKero(this, true, model);
        jk.setVisible(true);
    }//GEN-LAST:event_jmKerdesSzerkesztoActionPerformed
    private void ellenor(int v){
        int valasz = v;
        
        if (!helyes) {
            tfKerdezo.setText("A játék véget ért!");
        }
        if (valasz == kerdezo.getKerdes().getHelyesvalasz()) {
            tfKerdezo.setText("A válasz helyes! Jöhet a következő?");
            nyeremeny--;
            kerdesSzam++;

        } else {

            int i = 14;
            if (nyeremeny <= 11 && nyeremeny > 6) {
                i = 10;
            } else if (nyeremeny <= 6 && nyeremeny > 0) {
                i = 5;
            } else if (nyeremeny == 0) {
                i = 0;
            }
            tfKerdezo.setText(" Rossz válasz, a játék véget ért, nyereményed:" + nyeremenyek[i]);
            helyes = false;

        }
        
    }
    private void btnValasz0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz0ActionPerformed
        ellenor(0);
    }//GEN-LAST:event_btnValasz0ActionPerformed

    private void btnValasz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz1ActionPerformed
        ellenor(1);
    }//GEN-LAST:event_btnValasz1ActionPerformed

    private void btnValasz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz2ActionPerformed
        ellenor(2);
    }//GEN-LAST:event_btnValasz2ActionPerformed

    private void btnValasz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz3ActionPerformed
        ellenor(3);
    }//GEN-LAST:event_btnValasz3ActionPerformed

    private void btnIgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgenActionPerformed
        if (nyeremeny > 0 && helyes) {
            jatek();
        } else if (nyeremeny == 0 && helyes) {
            tfKerdezo.setText("Megnyerted a főnyereményt: " + nyeremenyek[nyeremeny] + ".");
        } else if (!helyes) {
            tfKerdezo.setText("A játék véget ért!");
        }

    }//GEN-LAST:event_btnIgenActionPerformed

    private void btnNemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNemActionPerformed

        int i = 14;
        if (nyeremeny > 14) {
            tfKerdezo.setText("Nem nyertél!");
        }
        if (helyes && nyeremeny <= 14) {
            tfKerdezo.setText("A nyereményed: " + nyeremenyek[nyeremeny] + ".");
            helyes = false;
        } else if (nyeremeny <= 11 && nyeremeny > 6) {
            i = 10;
            tfKerdezo.setText("A nyereményed: " + nyeremenyek[i] + ".");
        } else if (nyeremeny <= 6 && nyeremeny > 0) {
            i = 5;
            tfKerdezo.setText("A nyereményed: " + nyeremenyek[i] + ".");
        } else if (nyeremeny == 0) {
            i = 0;
            tfKerdezo.setText("A nyereményed: " + nyeremenyek[i] + ".");
        }

        helyes = false;


    }//GEN-LAST:event_btnNemActionPerformed

    private void btnTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonActionPerformed
        if (kerdes == null) {
            JOptionPane.showMessageDialog(this, "Ezt elhasználtad a semmire!?", "Telefonos segítség", JOptionPane.OK_OPTION);
        }
        
        String betu = "";
        int szam = kerdes.getHelyesvalasz();
        switch (szam) {
            case 0:
                betu = "A";
                break;
            case 1:
                betu = "B";
                break;
            case 2:
                betu = "C";
                break;
            case 3:
                betu = "D";
                break;
        }

        if (telo) {
            JOptionPane.showMessageDialog(this, "Szevasz Cimbi, a helyes válasz szerintem: " + betu + "!", "Telefonos segítség", JOptionPane.OK_OPTION);
        }
        telo = false;
        
    }//GEN-LAST:event_btnTelefonActionPerformed

    private void btnKozonsegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKozonsegActionPerformed
        if (kerdes == null) {
            JOptionPane.showMessageDialog(this, "Ezt elhasználtad a semmire!?", "Közönség véleménye", JOptionPane.OK_OPTION);
        } else if (kozonseg) {
            jdKozonseg kk = new jdKozonseg(this, true);
            kk.setVisible(true);
        }
        kozonseg = false;

    }//GEN-LAST:event_btnKozonsegActionPerformed

    private void btnFelezoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFelezoActionPerformed
        if (kerdes == null && felezo == true) {
            JOptionPane.showMessageDialog(this, "Ezt elhasználtad a semmire!?", "Felező", JOptionPane.OK_OPTION);
        }
        int valasz = kerdes.getHelyesvalasz();
        if (valasz == 0 && felezo == true) {
            btnValasz1.setText("Ez biztos nem jó!");
            btnValasz3.setText("Ezt se válszd, mert megjárod!");
        }
        if (valasz == 1 && felezo == true) {
            btnValasz2.setText("Ez biztos nem jó!");
            btnValasz3.setText("Ezt se válszd, mert megjárod!");
        }
        if (valasz == 2 && felezo == true) {
            btnValasz0.setText("Ez biztos nem jó!");
            btnValasz3.setText("Ezt se válszd, mert megjárod!");
        }
        if (valasz == 3 && felezo == true) {
            btnValasz0.setText("Ez biztos nem jó!");
            btnValasz2.setText("Ezt se válszd, mert megjárod!");
        }
        felezo = false;
        
    }//GEN-LAST:event_btnFelezoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFelezo;
    private javax.swing.JButton btnIgen;
    private javax.swing.JToggleButton btnKozonseg;
    private javax.swing.JButton btnNem;
    private javax.swing.JToggleButton btnTelefon;
    private javax.swing.JButton btnValasz0;
    private javax.swing.JButton btnValasz1;
    private javax.swing.JButton btnValasz2;
    private javax.swing.JButton btnValasz3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmJatek;
    private javax.swing.JMenuItem jmKerdesSzerkeszto;
    private javax.swing.JMenu jmKerdesek;
    private javax.swing.JMenuItem jmKilepes;
    private javax.swing.JMenuItem jmUjJatek;
    private javax.swing.JList<String> lstNyeremeny;
    private javax.swing.JTextField tfKerdes;
    private javax.swing.JTextField tfKerdezo;
    // End of variables declaration//GEN-END:variables
}
