/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loimgui;

import java.awt.Frame;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.IModel;
import model.Kerdesek;

/**
 *
 * @author Bodnár Tamás <tms.bodnar@gmail.com> | www.kalandlabor.hu
 */
public class KerdesSzerkeszto extends javax.swing.JDialog {
        private IModel model;
        private Frame parent;
        Vector<Kerdesek> kerdesek;
        private DefaultTableModel dtm;
        
    /**
     * Creates new form KerdesSzerkeszto
     */
    public KerdesSzerkeszto(java.awt.Frame parent, boolean modal, IModel model){
        super(parent, modal);
        initComponents();
        this.model = model;
        this.parent = parent;
        dtm = (DefaultTableModel) tblKerdesek.getModel();
        setLocationRelativeTo(parent);
        updateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1Valasz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf0Valasz = new javax.swing.JTextField();
        tf2Valasz = new javax.swing.JTextField();
        tf3Valasz = new javax.swing.JTextField();
        btnSzerkeszt = new javax.swing.JButton();
        btnHozaad = new javax.swing.JButton();
        btnTorol = new javax.swing.JButton();
        btnMegsem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rbtn0Valasz = new javax.swing.JRadioButton();
        rbtn2Valasz = new javax.swing.JRadioButton();
        rbtn1Valasz = new javax.swing.JRadioButton();
        rbtn3valasz = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKerdesek = new javax.swing.JTable();
        btnFrissit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("A kérdések:");

        jLabel3.setText("'A' válasz:");

        jLabel4.setText("'B' válasz:");

        jLabel5.setText("'C' válasz:");

        jLabel6.setText("'D' válasz:");

        btnSzerkeszt.setText("Szerkeszt");
        btnSzerkeszt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzerkesztActionPerformed(evt);
            }
        });

        btnHozaad.setText("Hozzáad");
        btnHozaad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHozaadActionPerformed(evt);
            }
        });

        btnTorol.setText("Töröl");
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });

        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        jLabel2.setText("Helyes?");

        buttonGroup1.add(rbtn0Valasz);

        buttonGroup1.add(rbtn2Valasz);

        buttonGroup1.add(rbtn1Valasz);

        buttonGroup1.add(rbtn3valasz);

        tblKerdesek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Kérdés"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblKerdesek);
        tblKerdesek.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblKerdesek.getColumnModel().getColumnCount() > 0) {
            tblKerdesek.getColumnModel().getColumn(0).setMinWidth(50);
            tblKerdesek.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblKerdesek.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnFrissit.setText("Frissít");
        btnFrissit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrissitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf2Valasz, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(btnSzerkeszt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnHozaad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTorol, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMegsem, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf0Valasz, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                            .addComponent(tf1Valasz)))
                                    .addComponent(tf3Valasz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn3valasz)
                                    .addComponent(rbtn2Valasz)
                                    .addComponent(rbtn1Valasz)
                                    .addComponent(rbtn0Valasz)
                                    .addComponent(jLabel2)))
                            .addComponent(btnFrissit)))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFrissit, btnHozaad, btnMegsem, btnSzerkeszt, btnTorol});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn0Valasz)
                            .addComponent(tf0Valasz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf1Valasz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtn1Valasz))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf2Valasz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtn2Valasz))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf3Valasz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtn3valasz))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFrissit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHozaad)
                        .addGap(18, 18, 18)
                        .addComponent(btnSzerkeszt)
                        .addGap(18, 18, 18)
                        .addComponent(btnTorol)
                        .addGap(18, 18, 18)
                        .addComponent(btnMegsem))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrissitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrissitActionPerformed

                int selected = tblKerdesek.getSelectedRow();
                if (selected >=  0 && selected <= tblKerdesek.getRowCount()){
                Kerdesek kerdes = kerdesek.elementAt(selected);
                   tf0Valasz.setText(kerdes.getValasz0());
                   tf1Valasz.setText(kerdesek.elementAt(selected).getValasz1());
                   tf2Valasz.setText(kerdesek.elementAt(selected).getValasz2());
                   tf3Valasz.setText(kerdesek.elementAt(selected).getValasz3());
                   int helyes = kerdesek.elementAt(selected).getHelyesvalasz();
                   switch (helyes){
                       case 0 : rbtn0Valasz.setSelected(true); break;
                       case 1 : rbtn1Valasz.setSelected(true);break;
                       case 2 : rbtn2Valasz.setSelected(true);break;
                       case 3 : rbtn3valasz.setSelected(true);break;                   
                   }
            }
    }//GEN-LAST:event_btnFrissitActionPerformed

    private void btnHozaadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHozaadActionPerformed
        Kerdesek kerdes = new Kerdesek();
        jdHozzaad kh = new jdHozzaad(parent, true, kerdes);
        kh.setVisible(true);
        if(kh.isMentes()){
            try {
                model.addKerdes(kerdes);
                updateTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(parent, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHozaadActionPerformed

    private void btnSzerkesztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzerkesztActionPerformed
        int selected = tblKerdesek.getSelectedRow();
        if (selected >=  0 && selected <= tblKerdesek.getRowCount()){
            Kerdesek kerdes = kerdesek.elementAt(selected);
            jdHozzaad hk = new jdHozzaad(parent, true,kerdes );
            hk.setVisible(true);
            if(hk.isMentes()){
                try {
                    model.updateKerdes(kerdes);
                    updateTable();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(parent, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else JOptionPane.showMessageDialog(parent, "Nincs kiválasztva kérdés!", "Hiányzó adat!", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnSzerkesztActionPerformed

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed
        int selected = tblKerdesek.getSelectedRow();
        if ( selected >= 0 && selected <= tblKerdesek.getRowCount()){
            Kerdesek kerdes = kerdesek.elementAt(selected);
            int valasz = JOptionPane.showConfirmDialog(parent, "Biztosan törlöd?", "Törlési megerősítés", JOptionPane.YES_NO_OPTION);
            if (valasz == 0){
                try {
                    model.removeKerdes(kerdes);
                    updateTable();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(parent, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else JOptionPane.showMessageDialog(parent, "Nincs kiválasztva kérdés!", "Hiányzó adat!", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_btnTorolActionPerformed

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnMegsemActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFrissit;
    private javax.swing.JButton btnHozaad;
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnSzerkeszt;
    private javax.swing.JButton btnTorol;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtn0Valasz;
    private javax.swing.JRadioButton rbtn1Valasz;
    private javax.swing.JRadioButton rbtn2Valasz;
    private javax.swing.JRadioButton rbtn3valasz;
    private javax.swing.JTable tblKerdesek;
    private javax.swing.JTextField tf0Valasz;
    private javax.swing.JTextField tf1Valasz;
    private javax.swing.JTextField tf2Valasz;
    private javax.swing.JTextField tf3Valasz;
    // End of variables declaration//GEN-END:variables

    private void updateTable() {
        dtm.getDataVector().removeAllElements();
            try {
                kerdesek = model.getAllKerdes();                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(parent, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
            }
            
            for(Kerdesek k : kerdesek){
                Vector sor = new Vector();
                sor.add(k.getIdkerdesek());
                sor.add(k.getKerdes());
                dtm.addRow(sor);
            }
            
            }

                   }
    

